/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chelapsAutomation.app.src.test.java.chelapsautomation;

import chelapsAutomation.app.src.main.java.chelapsautomation.App;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        
    }

    private void assertNotNull(String greeting, String string) {

        throw new UnsupportedOperationException("Unimplemented method 'assertNotNull'");
    }
}
